# Generated by Django 3.0.1 on 2020-07-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sport_Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teams', models.CharField(help_text='teams playing against each other', max_length=200)),
                ('Type', models.CharField(help_text='sport type ', max_length=200)),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('Venue', models.CharField(help_text='vanue of the sport classes ', max_length=200)),
                ('Description', models.CharField(help_text='About the sport game', max_length=50)),
            ],
        ),
    ]
