# Generated by Django 3.0.1 on 2020-07-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_volunteer_programs'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(help_text='title of the news', max_length=200)),
                ('Nimage', models.ImageField(upload_to='newsIamge')),
                ('Nbody', models.CharField(help_text='news body', max_length=500)),
                ('NdateTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
