# Generated by Django 3.0.1 on 2020-07-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(help_text='sport type ', max_length=200)),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('Venue', models.CharField(help_text='vanue of the sport classes ', max_length=200)),
                ('sportImage', models.ImageField(upload_to='sportimages')),
                ('sportvideo', models.FileField(null=True, upload_to='sportvid')),
                ('instructure', models.CharField(help_text='Instruture', max_length=30)),
            ],
        ),
    ]
