# Generated by Django 3.0.1 on 2020-07-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_sportsummar'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200)),
                ('emails', models.EmailField(max_length=200)),
                ('usercomments', models.CharField(max_length=200)),
            ],
        ),
    ]
