# Generated by Django 3.0.1 on 2020-06-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(help_text='title of the news', max_length=200)),
                ('Nimage', models.ImageField(upload_to='newsIamge')),
                ('Nbody', models.CharField(help_text='news body', max_length=500)),
                ('NdateTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(help_text='sport type ', max_length=200)),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('Venue', models.CharField(help_text='vanue of the sport classes ', max_length=200)),
                ('sportImage', models.ImageField(upload_to='sportimages')),
                ('sportvideo', models.FileField(null=True, upload_to='sportvid')),
                ('instructure', models.CharField(help_text='Instruture', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='sportGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teams', models.CharField(help_text='teams playing against each other', max_length=200)),
                ('Type', models.CharField(help_text='sport type ', max_length=200)),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('Venue', models.CharField(help_text='vanue of the sport classes ', max_length=200)),
                ('Description', models.CharField(help_text='About the sport game', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(help_text='title of the programs', max_length=200)),
                ('Description', models.CharField(help_text='description of the program', max_length=400)),
            ],
        ),
    ]
